    local SpeedLib = loadstring(game:HttpGet("https://raw.githubusercontent.com/ahmadsgamer2/Speed-Hub-X/main/SpeedHubLib_V2/Library.lua"))()
    local Window = SpeedLib:MakeWindow({Title = "Speed Hub X | ".._G.Version,SubTitle = "by : AhmadV10",LoadText = "Speed Hub X",Flags = "Speed Hub X | PS99.lua"});
    Window:AddMinimizeButton({Button = {Image = "rbxassetid://16022917595"},UICorner = {true,CornerRadius = UDim.new(0.5, 0)},UIStroke = {false, {}}})
    local Home = Window:MakeTab({Name = "Home", Icon = "scan-face"})
    local Main = Window:MakeTab({Name = "Main", Icon = "Home"})
    local MiniGames = Window:MakeTab({Name = "MiniGames", Icon = "rbxassetid://15655884984"})
    local Eggs = Window:MakeTab({Name = "Eggs", Icon = "rbxassetid://15671358224"})
    Home:AddDiscordInvite({DiscordTitle = "Speed Hub X Official",DiscordIcon = "rbxassetid://16022917595",DiscordLink = _G.Discord})
    Home:AddSection({"Local Player"})
    Home:AddTextBox({Name = "WalkSpeed",Default = "",PlaceholderText = "Input",ClearText = false,Callback = function(value)game.Players.LocalPlayer.Character.Humanoid.WalkSpeed = value end})
    Home:AddTextBox({Name = "WalkJump",Default = "",PlaceholderText = "Input",ClearText = false,Callback = function(value)game.Players.LocalPlayer.Character.Humanoid.JumpPower = value end})
    Home:AddTextBox({Name = "Gravity",Default = "",PlaceholderText = "Input",ClearText = false,Callback = function(value)game.Workspace.Gravity = value end})
    Home:AddTextBox({Name = "HipHeight",Default = "",PlaceholderText = "Input",ClearText = false,Callback = function(value)game.Players.LocalPlayer.Character.Humanoid.HipHeight = value end})
    Main:AddSection({"Farming"})
    Main:AddToggle({Name = "Auto Get Tap",Default = false,Callback = function(value)task.spawn(function()getgenv().AutoFarm = value AutoFarm("AutoFarm")end) end})
    Main:AddToggle({Name = "Auto Farm Neareast",Default = false,Callback = function(value)task.spawn(function()getgenv().AutoFarmNeareast = value;AutoFarmNeareast("AutoFarmNeareast")end) end})
    Main:AddToggle({Name = "Get Fast Pets",Default = false,Callback = function(value)task.spawn(function()getgenv().GetFastPets = value GetFastPet("GetFastPets")end) end})
    Main:AddSection({"Collecter / Redeem"})
    Main:AddToggle({Name = "Auto Collect Orbs",Default = true,Callback = function(value)task.spawn(function()getgenv().AutoCollectOrbs = value AutoCollectOrbs("AutoCollectOrbs")end) end})
    Main:AddToggle({Name = "Auto Collect Lootbags",Default = true,Callback = function(value) task.spawn(function()getgenv().AutoCollectLootBags = value AutoCollectLootBags("AutoCollectLootBags")end) end}) 
    Main:AddToggle({Name = "Auto Redeem Rewards",Default = false,Callback = function(value) task.spawn(function()getgenv().AutoRedeemRewards = value AutoRedeemRewards("AutoRedeemRewards")end) end})
    MiniGames:AddSection({"MiniGames"})
    MiniGames:AddSection({"Farming Digsite"})
    MiniGames:AddDropdown({Name = "Select List",Options = {"Digsite","Advanced"},Default = {"Digsite"},MultSelect = false,Callback = function(value) getgenv().SelectMethod = value end})
    MiniGames:AddToggle({Name = "Auto Farm Digsite [Block]",Default = false,Callback = function(value)task.spawn(function()getgenv().AutoDigsiteBlock = value AutoDigsiteBlock("AutoDigsiteBlock")end) end}) 
    MiniGames:AddToggle({Name = "Auto Farm Digsite [Chest]",Default = false,Callback = function(value)task.spawn(function()getgenv().AutoDigsiteChest = value AutoDigsiteChest("AutoDigsiteChest")end) end})
    MiniGames:AddToggle({Name = "Auto Farm Digsite [Other]",Default = false,Callback = function(value)task.spawn(function()getgenv().AutoDigsite = value AutoDigsite("AutoDigsite")end) end})
    MiniGames:AddSection({"Farming Stairs"})
    MiniGames:AddToggle({Name = "Auto Farm Stairs",Default = false,Callback = function(value)task.spawn(function()getgenv().AutoStairs = value AutoStairs("AutoStairs")end) end})
    Eggs:AddSection({"Eggs"})
    Eggs:AddDropdown({Name = "Select List Eggs",Options = ETable,Default = {""},MultSelect = false,Callback = function(value)getgenv().SelectEggs = value end})
    Eggs:AddSlider({Name = "Amount Egg",MinValue = 1,MaxValue = 100,Default = 1,Increase = 1,Callback = function(value) getgenv().EggsA = value end})
    Eggs:AddSlider({Name = "Auto Open Eggs Delay",MinValue = 0,MaxValue = 100,Default = 0,Increase = 1,Callback = function(value) getgenv()["Auto Open Eggs Delay"] = value end})
    Eggs:AddToggle({Name = "Auto Open Eggs",Default = false,Callback = function(value)task.spawn(function()getgenv().AutoOpenEggs = value AutoOpenEggs("AutoOpenEggs")end) end})
